---
name: Publish new release to npmjs
on:
  release:
    types: [created]

jobs:
  check-readme-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for README and CHANGELOG changes
        run: |
          if ! git diff --quiet HEAD~ HEAD -- README.md CHANGELOG.md; then
            echo "README and/or CHANGELOG have been modified. Proceeding with deployment."
          else
            echo "README and/or CHANGELOG have not been modified. Terminating deployment."
            exit 1
          fi

  publish:
    needs: check-readme-and-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Engine
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Node dependencies
        run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
